feat: Add needed fields for imagecraft
canonical/craft-archives pull request #120
Opened 2024-06-25 13:07 UTC by upils

- [x] Have you followed the guidelines for contributing?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `tox`?

-----

Implement the FO169 spec to adapt craft-archives to imagecraft.

I also documented the `priority` field to be closer to the documentation on snapcraft.io.

2024-06-26 12:19 UTC, tigarmo requested changes
thanks! This is very good, I added some mostly minor comments

2024-06-26 12:19 UTC, tigarmo commented on craft_archives/repo/package_repository.py
> +                url=url, message="specify either suites or series and pocket."
maybe we can make the message a bit clearer? Something like `suites cannot be used with series and pocket`

2024-06-26 12:19 UTC, tigarmo commented on craft_archives/repo/apt_sources_manager.py
What about support for series and pocket when constructing the deb822 file? Is the idea to do that in a follow-up PR? I'd be fine with that

2024-06-26 12:19 UTC, tigarmo commented on docs/reference/repo_properties.rst
> +     "fingerprint"). The Craft Application will first look for the corresponding
I think we need to drop this sentence referring to `<project>/snap/keys` from these docs - it only applies to snapcraft

2024-06-26 12:19 UTC, tigarmo commented on docs/reference/repo_properties.rst
> +         The Application will look for a corresponding key at
here too

2024-06-26 12:19 UTC, tigarmo commented on docs/reference/repo_properties.rst
> +   - Description: Pocket to get packages from, must one of: ``release``,
```suggestion
   - Description: Pocket to get packages from, must be one of: ``release``,
```

2024-06-27 07:09 UTC, upils commented on craft_archives/repo/package_repository.py
> +                url=url, message="suites or series and pocket must be specified when using components."
You are right, this is confusing. I will fix that.

2024-06-27 07:24 UTC, upils commented on craft_archives/repo/apt_sources_manager.py
Good catch, I forgot about it! Let me add it if this is not too big of a change and ask for another review.

2024-06-27 10:10 UTC, upils commented on craft_archives/repo/apt_sources_manager.py
It is done. Let me know if this is what you had in mind. the `_get_suites()` function is generating a suites list tailored to what is expected in an official ubuntu image (so for example only `<series>-security` if the security pocket is given, etc.). Let me know if this is working for you. This is more opinionated than the implementation with the `suites` arg, where users can set whatever they want, even if it does make any sense "package-wise".

2024-07-02 11:38 UTC, tigarmo commented on craft_archives/repo/apt_sources_manager.py
thanks! Do you happen to have a reference to the logic of which suites get used for which pockets?

2024-07-02 11:57 UTC, upils commented
https://github.com/canonical/craft-archives/pull/120#discussion_r1662363606 This is the same logic we implemented in ubuntu-image (see https://github.com/canonical/ubuntu-image/blob/main/internal/imagedefinition/image_definition.go#L328). You can find documentation here https://canonical-ubuntu-packaging-guide.readthedocs-hosted.com/en/latest/explanation/archive/#pockets

2024-07-02 11:57 UTC, upils commented on craft_archives/repo/apt_sources_manager.py
This is the same logic we implemented in ubuntu-image (see https://github.com/canonical/ubuntu-image/blob/main/internal/imagedefinition/image_definition.go#L328). You can find documentation here https://canonical-ubuntu-packaging-guide.readthedocs-hosted.com/en/latest/explanation/archive/#pockets

2024-07-02 12:07 UTC, tigarmo commented on craft_archives/repo/apt_sources_manager.py
thanks. Do you think it's worth documenting this logic?

2024-07-03 06:35 UTC, upils commented on craft_archives/repo/apt_sources_manager.py
I think we should avoid duplicating this documentation. But I can this link to the `pocket` field in the documentation to make it clear to users how this is supposed to behave.

2024-07-03 11:34 UTC, tigarmo commented on craft_archives/repo/apt_sources_manager.py
Yes I'm fine with just adding a link

2024-07-05 13:08 UTC, cmatsuoka approved these changes

2024-07-05 13:08 UTC, cmatsuoka commented on craft_archives/repo/apt_sources_manager.py
> +)
This could be a single line.

2024-07-05 13:09 UTC, merged