fix: fix tests on arm64
canonical/craft-archives pull request #145
Opened 2024-12-12 02:17 UTC by lengau

Fixes #144

2025-01-15 07:58 UTC, upils requested changes

2025-01-15 07:58 UTC, upils commented on .github/workflows/qa.yaml
> +      fast-test-platforms: '["jammy", ["noble", "amd64"], ["noble", "arm64"]]'
Is that intentional to not also explicitly set arm64 and amd64 for jammy here?

2025-01-18 03:26 UTC, lengau commented on .github/workflows/qa.yaml
> +      fast-test-platforms: '["jammy", ["noble", "amd64"], ["noble", "arm64"]]'
Yes. That way we run on both architectures on noble, but we just check whatever's available first on jammy.

2025-01-20 08:39 UTC, upils approved these changes

2025-06-06 19:11 UTC, tigarmo approved these changes

2025-06-06 19:12 UTC, merged